---
name: Image-Size
version: 3.01
author:
  - 'Randy J. Ray <rjray@blackperl.com>'
abstract: A library to extract height/width from images
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  File::Spec: 0
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Image::Size:
    file: lib/Image/Size.pm
    version: 3.01
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
