---
name: Image-Size
version: 3.220
author:
  - 'Randy J. Ray <rjray@blackperl.com>'
abstract: A library to extract height/width from images
license: perl
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Image-Size
  homepage: http://search.cpan.org/dist/Image-Size
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rjray/image-size
build_requires:
  Module::Build: 0.28
  Test::More: 0.80
requires:
  File::Spec: 0.8
  perl: 5.006
recommends:
  Compress::Zlib: 2
configure_requires:
  Module::Build: 0.35
provides:
  Image::Size:
    file: lib/Image/Size.pm
    version: 3.220
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
