---
name: Image-Size
version: 3.2
author:
  - 'Randy J. Ray <rjray@blackperl.com>'
abstract: A library to extract height/width from images
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Spec: 0.8
  perl: 5.006
build_requires:
  Module::Build: 0.28
  Test::More: 0.80
recommends:
  Compress::Zlib: 2
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Image::Size:
    file: lib/Image/Size.pm
    version: 3.2
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
