---
abstract: 'A library to extract height/width from images'
author:
  - 'Randy J. Ray <rjray@blackperl.com>'
build_requires:
  Module::Build: 0.28
  Test::More: 0.80
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Image-Size
provides:
  Image::Size:
    file: lib/Image/Size.pm
    version: 3.232
recommends:
  Compress::Zlib: 2
requires:
  File::Spec: 0.8
  perl: 5.006001
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Image-Size
  homepage: http://search.cpan.org/dist/Image-Size
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rjray/image-size
version: 3.232
