--- #YAML:1.0
name:                Image-Size
version:             3.1
abstract:            A library to extract height/width from images
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    File::Spec:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Randy J. Ray (rjray@blackperl.com)
